// Runs after `vite build`:
//  1. writes dist/.htaccess (Apache/cPanel; noindex on every preview build), robots.txt and sitemap.xml
//  2. production builds FAIL if any "[CONFIRM" string remains in dist/, or if an
//     indexable page still carries a noindex robots meta.

import { globSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const dist = resolve(import.meta.dirname, '..', 'dist');
const business = JSON.parse(readFileSync(resolve(import.meta.dirname, '..', 'src/data/business.json'), 'utf8'));
const production = process.env.SITE_ENV === 'production';
const origin = business.url.replace(/\/$/, '');

const pages = globSync('**/*.html', { cwd: dist });
const errors = [];

// cPanel / Apache: security headers, noindex on previews, 404 page, compression, caching.
// Redirects and 410s (section 10) are appended here in Phase 6.
const htaccess = [
  '# Generated by scripts/postbuild.js — do not edit on the server.',
  'Options -Indexes',
  'DirectoryIndex index.html',
  'ErrorDocument 404 /404.html',
  '',
  '<IfModule mod_rewrite.c>',
  '  RewriteEngine On',
  ...(production
    ? [
        '  # Force HTTPS on the live domain.',
        '  RewriteCond %{HTTPS} !=on',
        '  RewriteCond %{HTTP:X-Forwarded-Proto} !=https',
        '  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]',
      ]
    : []),
  '</IfModule>',
  '',
  '<IfModule mod_headers.c>',
  '  Header always set X-Content-Type-Options "nosniff"',
  '  Header always set Referrer-Policy "strict-origin-when-cross-origin"',
  '  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"',
  '  Header always set X-Frame-Options "DENY"',
  ...(production ? [] : ['  Header always set X-Robots-Tag "noindex, nofollow"']),
  '  <FilesMatch "\\.html$">',
  '    Header set Cache-Control "no-cache"',
  '  </FilesMatch>',
  '</IfModule>',
  '',
  '<IfModule mod_deflate.c>',
  '  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/json image/svg+xml text/xml application/xml text/plain',
  '</IfModule>',
  '',
  '<IfModule mod_mime.c>',
  '  AddType image/avif .avif',
  '  AddType image/webp .webp',
  '  AddType font/woff2 .woff2',
  '</IfModule>',
  '',
];
writeFileSync(resolve(dist, '.htaccess'), htaccess.join('\n'));
// Hashed build assets never change: cache for a year.
writeFileSync(
  resolve(dist, 'assets/.htaccess'),
  '<IfModule mod_headers.c>\n  Header set Cache-Control "public, max-age=31536000, immutable"\n</IfModule>\n',
);

const indexable = [];
for (const page of pages) {
  const html = readFileSync(resolve(dist, page), 'utf8');
  if (production && html.includes('[CONFIRM')) errors.push(`[CONFIRM] placeholder left in ${page}`);
  const noindex = /<meta name="robots" content="noindex/.test(html);
  if (page === '404.html' || noindex) continue;
  indexable.push('/' + page.replace(/index\.html$/, ''));
}

writeFileSync(
  resolve(dist, 'robots.txt'),
  // Previews stay crawlable so crawlers can see the X-Robots-Tag/meta noindex and drop the URLs.
  production ? `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n` : 'User-agent: *\nAllow: /\n',
);

const urls = indexable
  .sort()
  .map((path) => `  <url><loc>${origin}${path}</loc></url>`)
  .join('\n');
writeFileSync(
  resolve(dist, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
);

if (production && indexable.length === 0) errors.push('Production build has no indexable pages.');

if (errors.length) {
  console.error(`\nBuild gate FAILED (${production ? 'production' : 'preview'}):\n - ${errors.join('\n - ')}\n`);
  process.exit(1);
}
console.log(
  `postbuild: ${pages.length} pages, ${indexable.length} in sitemap, env=${production ? 'production' : 'preview'}`,
);
