// Runs after `vite build`:
//  - cpanel target: writes dist/.htaccess (HTTPS, clean URLs, legacy redirects, 410s for the
//    old demo content, caching, security headers, custom 404)
//  - both targets: robots.txt and sitemap.xml naming the live domain
//  - reports how many [CONFIRM] / PLACEHOLDER items remain (npm run package refuses to ship them)

import { globSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { site } from '../src/data/site.js';
import { resolveDeployment } from './lib/deploy.mjs';

const dist = resolve(import.meta.dirname, '..', 'dist');
const deploy = resolveDeployment();
const origin = site.canonicalOrigin;
const pages = globSync('**/*.html', { cwd: dist });

// ---------------------------------------------------------------- .htaccess (cPanel only)
const CSP = [
  "default-src 'self'",
  "script-src 'self' https://www.googletagmanager.com",
  "style-src 'self'",
  "font-src 'self'",
  "img-src 'self' data: https://*.google-analytics.com https://*.googletagmanager.com",
  "connect-src 'self' https://formspree.io https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com",
  "form-action 'self' https://formspree.io",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
].join('; ');

// Old WordPress URLs (MASTER_PROMPT.md §10). Real pages move with a single 301; demo
// content that never belonged to Regardin is answered with 410 Gone.
const REDIRECTS = [
  ['about-us', '/about/'],
  ['our-services', '/services/'],
  ['contact-us', '/contact/'],
  ['our-portfolio', '/projects/'],
  ['our-team', '/about/'],
];
const GONE = [
  'why-do-i-need-to-use-financial',
  'why-your-sales-forecast-is-off',
  '6-tips-to-retain-your-top-sales-talent',
  'what-the-martian-can-teach-sales',
  'portfolios(?:/.*)?',
  'portfolios_category(?:/.*)?',
  'category(?:/.*)?',
  'tag(?:/.*)?',
  'author(?:/.*)?',
  'tf_header_footer(?:/.*)?',
  'feed',
  'comments/feed',
  'blog',
];

const htaccess = `# Generated by scripts/postbuild.js — edit that file, not this one on the server.
Options -Indexes -MultiViews
DirectoryIndex index.html
DirectorySlash On
ErrorDocument 404 /404.html
ErrorDocument 410 /404.html

<IfModule mod_rewrite.c>
  RewriteEngine On

  # HTTPS (also behind a proxy or load balancer that sets X-Forwarded-Proto).
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # One host: www → bare domain.
  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]

  # Clean URLs: /page/index.html → /page/
  RewriteCond %{THE_REQUEST} \\s/+((?:[^\\s?]*/)?)index\\.html[\\s?] [NC]
  RewriteRule ^ /%1 [L,R=301]

  # Clean URLs: /page.html → /page/ when that folder exists
  RewriteCond %{THE_REQUEST} \\s/+([^\\s?]+)\\.html[\\s?] [NC]
  RewriteCond %{DOCUMENT_ROOT}/%1/index.html -f
  RewriteRule ^ /%1/ [L,R=301]

  # Old site pages → new pages
${REDIRECTS.map(([from, to]) => `  RewriteRule ^${from}/?$ ${to} [L,R=301]`).join('\n')}

  # Demo content from the old template: gone for good
${GONE.map((p) => `  RewriteRule ^${p}/?$ - [G,L]`).join('\n')}
</IfModule>

<IfModule mod_headers.c>
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  Header always set X-Frame-Options "DENY"
  Header always set Content-Security-Policy "${CSP}"
  Header always set Strict-Transport-Security "max-age=31536000" env=HTTPS
  <FilesMatch "\\.(html|xml|txt)$">
    Header set Cache-Control "no-cache"
  </FilesMatch>
  <FilesMatch "\\.(jpe?g|png|webp|avif|svg|ico|woff2)$">
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/json image/svg+xml text/xml application/xml text/plain
</IfModule>

<IfModule mod_mime.c>
  AddType image/avif .avif
  AddType image/webp .webp
  AddType font/woff2 .woff2
  AddType application/manifest+json .webmanifest
</IfModule>
`;

if (deploy.target === 'cpanel') {
  writeFileSync(resolve(dist, '.htaccess'), htaccess);
  // Hashed build output never changes: cache for a year.
  writeFileSync(
    resolve(dist, 'assets/build/.htaccess'),
    '<IfModule mod_headers.c>\n  Header set Cache-Control "public, max-age=31536000, immutable"\n</IfModule>\n',
  );
}

// ---------------------------------------------------------------- robots and sitemap
const indexable = [];
let todoCount = 0;
for (const page of pages) {
  const html = readFileSync(resolve(dist, page), 'utf8');
  todoCount += (html.match(/\[CONFIRM:/g) || []).length;
  const noindex = /<meta name="robots" content="noindex/.test(html);
  if (page === '404.html' || page.startsWith('thank-you/')) continue;
  if (noindex && deploy.target === 'cpanel') continue;
  indexable.push('/' + page.replace(/index\.html$/, ''));
}

writeFileSync(
  resolve(dist, 'robots.txt'),
  deploy.target === 'cpanel'
    ? `User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`
    : // The preview's pages all carry noindex; crawlers must be allowed in to see it.
      'User-agent: *\nAllow: /\n',
);

const today = new Date().toISOString().slice(0, 10);
writeFileSync(
  resolve(dist, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexable
  .sort()
  .map((path) => `  <url><loc>${origin}${path}</loc><lastmod>${today}</lastmod></url>`)
  .join('\n')}
</urlset>
`,
);

console.log(
  `postbuild: ${pages.length} pages, ${indexable.length} in sitemap, target=${deploy.target}, ` +
    `${todoCount} [CONFIRM] markers on pages (see docs/TODO_CONFIRM.md)`,
);
